### ISSUE TITLE
全局扩展异常

### ISSUE THREAD

**Issue by BAKA24QWQ** [Hakoyu/StarsectorTools#10]
全局扩展异常 System.Private.CoreLib !!!警告!!!
如果你看到了这个错误,说明这是扩展中意料之外的情况
可能会影响扩展的正常运行,建议查看日志并提交issue至扩展开发者.

System.IO.IOException: The process cannot access the file 'D:\远行星号\starsector-core\starsector.log' because it is being used by another process.
   at StarsectorToolbox.ViewModels.CrashReporter.CrashReporterWindowViewModel.GetLines() in StarsectorToolbox\ViewModels\CrashReporter\CrashReporterWindowVMController.cs:line 251
   at StarsectorToolbox.ViewModels.CrashReporter.CrashReporterWindowViewModel.GetLastLog() in StarsectorToolbox\ViewModels\CrashReporter\CrashReporterWindowVMController.cs:line 240
   at StarsectorToolbox.ViewModels.CrashReporter.CrashReporterWindowViewModel.SetCrashReport() in StarsectorToolbox\ViewModels\CrashReporter\CrashReporterWindowVMController.cs:line 68
   at StarsectorToolbox.ViewModels.Main.MainWindowViewModel.ShowCrashReporterWindowReceive(Object recipient, ShowCrashReporterMessage message) in StarsectorToolbox\ViewModels\Main\MainWindowViewModel.cs:line 203
   at CommunityToolkit.Mvvm.Messaging.Internals.MessageHandlerDispatcher.For`2.Invoke(Object recipient, Object message)
   at CommunityToolkit.Mvvm.Messaging.WeakReferenceMessenger.SendAll[TMessage](ReadOnlySpan`1 pairs, Int32 i, TMessage message)
   at CommunityToolkit.Mvvm.Messaging.WeakReferenceMessenger.Send[TMessage,TToken](TMessage message, TToken token)
   at CommunityToolkit.Mvvm.Messaging.IMessengerExtensions.Send[TMessage](IMessenger messenger, TMessage message)
   at StarsectorToolbox.ViewModels.GameSettings.GameSettingsPageViewModel.ShowCrashReporter() in StarsectorToolbox\ViewModels\GameSettings\GameSettingsPageViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at StarsectorToolbox.App.Main()

**Comment by Hakoyu** [comment]
啊 日志文件被其它进程占用...

**Comment by Hakoyu** [comment]
已在 b231918 修复
