### ISSUE TITLE
远行星号0.96a与0.95.1a的英文版与汉化版均无法被识别。

### ISSUE THREAD

**Issue by starsectorsc** [Hakoyu/StarsectorTools#14]
[StarsectorToolbox.ViewModels.Main.MainWindowViewModel.InitializeConfig] ERROR 设置文件错误,将恢复为默认设置 位置: STCore\Settings.toml
System.ComponentModel.Win32Exception (740): An error occurred trying to start process 'C:\Program Files (x86)\Fractal Softworks\Starsector\jre\bin\java.exe' with working directory 'C:\Program Files (x86)\Fractal Softworks\Starsector'. 请求的操作需要提升。
   at StarsectorToolbox.Models.GameInfo.GameInfo.TryGetJaveVersion(String javaFile) in StarsectorToolbox\Models\GameInfo\GameInfo.cs:line 188
   at StarsectorToolbox.Models.GameInfo.GameInfo.SetGameData(String gameDirectory) in StarsectorToolbox\Models\GameInfo\GameInfo.cs:line 77
   at StarsectorToolbox.Models.GameInfo.GameInfo.GetGameDirectory() in StarsectorToolbox\Models\GameInfo\GameInfo.cs:line 162
   at StarsectorToolbox.ViewModels.Main.MainWindowViewModel.FirstCreateConfig(String tomlFile) in StarsectorToolbox\ViewModels\Main\MainWindowVMController.cs:line 466
   at StarsectorToolbox.ViewModels.Main.MainWindowViewModel.InitializeConfig() in StarsectorToolbox\ViewModels\Main\MainWindowVMController.cs:line 399
[StarsectorToolbox.Views.Main.MainWindow..ctor] ERROR 初始化错误: MainWindowViewModel
System.Exception: 未确认游戏启动程序, 软件即将退出
   at StarsectorToolbox.ViewModels.Main.MainWindowViewModel..ctor(Boolean noop) in StarsectorToolbox\ViewModels\Main\MainWindowViewModel.cs:line 97
   at StarsectorToolbox.Views.Main.MainWindow..ctor() in StarsectorToolbox\Views\Main\MainWindow.xaml.cs:line 45

以上是现存Log原文，现存StarsectorToolbox.exe安装位置为“C:\Program Files (x86)\Fractal Softworks\Starsector\StarsectorToolbox.exe”，现存STCore文件夹安装位置为“C:\Program Files (x86)\Fractal Softworks\Starsector\STCore”，现存STExtension文件夹安装位置为“C:\Program Files (x86)\Fractal Softworks\Starsector\STExtension”，现存Log文件所处位置为“C:\Program Files (x86)\Fractal Softworks\Starsector\STCore\StarsectorToolbox.log”，现存游戏版本为0.95.1a-rc6汉化版，现存游戏安装包来源为[https://www.fossic.org/thread-3060-1-1.html](url)，未安装任何MOD。

上一个游戏版本为0.96a英文原版，上一个游戏安装包来源为[https://fractalsoftworks.com/category/releases/](url)，未安装任何MOD。上一次StarsectorToolbox.exe安装位置为“C:\Program Files\Starsector\StarsectorToolbox.exe”，上一次STCore文件夹安装位置为“C:\Program Files\Starsector\STCore”，上一次STExtension文件夹安装位置为“C:\Program Files\Starsector\STExtension”，上一个Log文件所处位置为“C:\Program Files\Starsector\STCore\StarsectorToolbox.log”。

**Comment by starsectorsc** [comment]
现有游戏版本与上一个游戏版本之本体均能够正常运行，系统信息为：

版本	Windows 10 家庭中文版
版本号	22H2
安装日期	‎2023/‎2/‎6
操作系统内部版本	19045.2965
体验	Windows Feature Experience Pack 1000.19041.1000.0
系统类型	64 位操作系统, 基于 x64 的处理器

已遵照[https://www.fossic.org/thread-7006-1-1.html](url)之提示确认了.NET6环境的安装，SDK版本为6.0.415，下载来源为[https://dotnet.microsoft.com/zh-cn/download/dotnet/6.0](url) 页面下的 [https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/sdk-6.0.415-windows-x64-installer](url)。

**Comment by starsectorsc** [comment]
现有游戏版本与上一个游戏版本之本体均能够正常运行，系统信息为：

版本	Windows 10 家庭中文版
版本号	22H2
安装日期	‎2023/‎2/‎6
操作系统内部版本	19045.2965
体验	Windows Feature Experience Pack 1000.19041.1000.0
系统类型	64 位操作系统, 基于 x64 的处理器

已遵照[https://www.fossic.org/thread-7006-1-1.html](url)之提示确认了.NET6环境的安装，SDK版本为6.0.415，下载来源为[https://dotnet.microsoft.com/zh-cn/download/dotnet/6.0](url) 页面下的 [https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/sdk-6.0.415-windows-x64-installer](url)。
